
on:
  schedule:
    - cron: '0 8 * * *' # Every day at 8AM UTC
  workflow_dispatch: # workflow_dispatch enables the workflow to be triggered manually

jobs:
  meltano:
    runs-on: ubuntu-latest
    name: Meltano
    steps:
      # Checkout the repository so that a path to the action.yml can be used
      - uses: actions/checkout@v2
      # Get the database files from the previous run, if exists
      - name: Download latest SQLite database artifact
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          workflow: ${{ github.workflow }}
          branch: main
          name: meltano.db
          path: ${{ github.workspace }}
          workflow_conclusion: completed # Download artifacts from the latest completed run, even if it failed. This enables Meltano to start off from where a tap failed.
      - name: Meltano
        if: always() # Always run this step even if the prior failed due to no artifact found (this should only take effect if first time running)
        uses: ./
        env:
          TARGET_SNOWFLAKE_ACCOUNT: ${{ secrets.TARGET_SNOWFLAKE_ACCOUNT }}
          TARGET_SNOWFLAKE_USERNAME: MELTANO
          TARGET_SNOWFLAKE_PASSWORD: ${{ secrets.TARGET_SNOWFLAKE_PASSWORD }}
          TARGET_SNOWFLAKE_DBNAME: MELTANO
          TARGET_SNOWFLAKE_WAREHOUSE: MELTANO
          TARGET_SNOWFLAKE_FILE_FORMAT: meltano.public.csv
          TAP_SMARTSHEET_SMARTSHEET_ACCESS_TOKEN: ${{ secrets.TAP_SMARTSHEET_SMARTSHEET_ACCESS_TOKEN }}

          MELTANO_DATABASE_URI: sqlite:////github/workspace/meltano.db
        with:
          args: meltano elt tap-smartsheet target-snowflake --job_id=meltano # job_id required to use incremental state, can be anything
      - name: Meltano Slack alert
        if: failure() # Only run if one of the previous steps fails
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|:warning: Workflow ${{ github.workflow }} has failed.>"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      # Upload the sqlite database containing incremental, bookmark state
      - name: Upload SQLite database artifact
        if: always() # Always run this step even if the prior failed
        uses: actions/upload-artifact@v2
        with:
          name: meltano.db
          path: ${{ github.workspace }}/meltano.db*
